name: release

on:
  push:
    tags:
      - '*'

jobs:

  linux:
    name: Build wheels for Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64, i686, aarch64, armv7l, s390x, ppc64le]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}
      - name: Build wheels
        run: uv build
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-linux-${{ matrix.target }}-py${{ matrix.python-version }}
          path: dist/*.whl

  musllinux:
    name: Build wheels for MuslLinux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64, i686, aarch64, armv7l]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}
      - name: Build wheels
        run: uv build
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-musllinux-${{ matrix.target }}-py${{ matrix.python-version }}
          path: dist/*.whl

  windows:
    name: Build wheels for Windows
    runs-on: windows-latest
    strategy:
      matrix:
        target: [x64, x86]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}
      - name: Build wheels
        run: uv build
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-windows-${{ matrix.target }}-py${{ matrix.python-version }}
          path: dist/*.whl

  macos:
    name: Build wheels for macOS
    runs-on: macos-latest
    strategy:
      matrix:
        target: [x86_64, aarch64]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}
      - name: Build wheels
        run: uv build
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-macos-${{ matrix.target }}-py${{ matrix.python-version }}
          path: dist/*.whl

  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [linux, musllinux, windows, macos]
    steps:
      - name: Download wheels
        uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Tarball the wheels
        run: tar -czf wheels.tar.gz dist/**/*.whl
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: wheels.tar.gz
          tag_name: ${{ github.ref }}
          name: ${{ github.ref }}
          body: ${{ github.event.release.body }}
          draft: false
          prerelease: false

  publish:
    name: Publish to PyPI
    if: startsWith(github.ref, 'refs/tags/')
    needs: [linux, musllinux, windows, macos]
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/mplstylize
    permissions:
      id-token: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Move wheels to dist
        run: |
          find dist/ -type f -name "*.whl" -exec mv {} dist/ \;
          find dist/ -type d -empty -delete
      - name: Show all files recursively
        run: ls -R .
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
